### ISSUE TITLE
I pulled the project and had it running, I registered a new manufacturer, But I then cannot Verify it as I'm not a Trusted Entity 

### ISSUE THREAD

**Issue by aka-Rakesh** [oggy107/AuthentiScan#5]
I pulled the project and had it running, and I registered a new manufacturer.
But I then cannot Verify it as I'm not a Trusted Entity
So where can I add my metamask address to become a verifier??
And if there even is a direct way to do so

**Comment by oggy107** [comment]
Hi Rakesh, sorry I did not documented this case. In order to add trusted entity you need to go to `/add-trusted-entity` route manually.
